# Generated by Django 5.1.5 on 2025-01-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
