# Generated by Django 5.1.5 on 2025-01-26 00:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Short Description'),
        ),
    ]
