# Generated by Django 5.1.5 on 2025-01-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='banner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='speakers/'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
