# Generated by Django 5.1.5 on 2025-01-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventday_eventsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
