# Generated by Django 5.1.5 on 2025-01-30 05:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PRIVACY', 'Privacy Policy'), ('TERMS', 'Terms & Conditions'), ('DISCLAIMER', 'Disclaimer'), ('PAYMENT', 'Payment Policy'), ('COOKIES', 'Cookies Policy'), ('REFUND', 'Refund Policy')], max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Policy Document',
                'verbose_name_plural': 'Policy Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
