# Generated by Django 5.1.5 on 2025-01-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organization.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the organization.', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Upload the organization logo.', null=True, upload_to='organization_logos/')),
                ('contact_email', models.EmailField(help_text='Primary contact email for the organization.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number.', max_length=15, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the organization.', null=True)),
                ('website', models.URLField(blank=True, help_text='Official website URL.', null=True)),
                ('social_media', models.JSONField(blank=True, help_text='Links to social media profiles (e.g., Facebook, Twitter).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last updated timestamp.')),
            ],
        ),
    ]
