# Generated by Django 5.1.5 on 2025-01-26 13:51

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('section_type', models.CharField(choices=[('HERO', 'Hero Section'), ('MISSION', 'Mission Statement'), ('TEAM', 'Team Members'), ('HISTORY', 'Our History'), ('VALUES', 'Core Values'), ('STATS', 'Statistics'), ('PARTNERS', 'Partners'), ('CTA', 'Call to Action')], max_length=20)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('video_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', django_ckeditor_5.fields.CKEditor5Field()),
                ('photo', models.ImageField(upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='aboutus.aboutussection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
